-- Update the block booking function to default to 'Paid' for internal system consistency
-- This ensures students can access the block they just booked immediately.

CREATE OR REPLACE FUNCTION public.book_4week_block(
  slot_uuid uuid,
  desired_start_date date,
  package_id text,
  notes text DEFAULT ''
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  inst_id uuid;
  student_name_val text;
BEGIN
  -- Get student name
  SELECT name INTO student_name_val FROM public.profiles WHERE id = auth.uid();

  -- Insert enrollments for the next 4 occurrences starting from desired_start_date
  -- We assume group_instances for these dates already exist (generated by admin)
  INSERT INTO public.enrollments (
    package_id,
    instance_id,
    student_id,
    student_name,
    notes,
    payment_status,
    enrolled_at
  )
  SELECT 
    package_id,
    gi.id,
    auth.uid(),
    COALESCE(student_name_val, 'Student'),
    notes,
    'Paid', -- Default to Paid for now
    now()
  FROM public.group_instances gi
  WHERE gi.slot_id = slot_uuid
    AND gi.session_date >= desired_start_date
    AND gi.session_date < (desired_start_date + interval '28 days')
  ON CONFLICT (instance_id, student_id) DO NOTHING;

  -- If no rows inserted, it might be because the group is full (handled by trigger/logic) 
  -- or instances don't exist.
END;
$$;